### ISSUE TITLE
cmd/govim: nil pointer dereference

### ISSUE THREAD

**Issue by frioux** [myitcv/govim#474]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 23 2019 11:56:08)
Included patches: 1-1912
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-uFQAgl/vim-8.1.1912=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm     

</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/frew/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/frew/go"
GOPROXY="https://proxy.golang.org"
GORACE=""
GOROOT="/home/frew/sdk/go1.12.9"
GOTMPDIR=""
GOTOOLDIR="/home/frew/sdk/go1.12.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/frew/code/leatherman/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/shm/go-build624485991=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What version/commit of `govim` are you using?
9ad6148ddeb041213b4535220468ebe0f912e812

### What is the output of `:messages` in Vim?
```
Error detected while processing function GOVIM_internal_Complete[2]..<SNR>30_callbackFunction:
line    4:
E605: Exception not caught: got error whilst handling GOVIM_internal_Complete: called to gopls.Completion failed: GetAST: unable to check package for file:///home/frew/code/zr0/infrastructure
/stevedore/debugshell.go: no packages found for file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go
Error detected while processing function GOVIM_internal_Complete[2]..<SNR>30_callbackFunction:
line    4:
E605: Exception not caught: got error whilst handling GOVIM_internal_Complete: caught panic: runtime error: invalid memory address or nil pointer dereference^@goroutine 217 [running]:^@github
.com/myitcv/govim.(*govimImpl).run.func8.1.1(0xc000043ef0, 0xc0000cc000)^@^I/home/frew/code/dotfiles/vim/pack/vanilla/start/govim/govim.go:513 +0x17d^@panic(0x602260, 0x801d10)^@^I/home/frew/
sdk/go1.12.9/src/runtime/panic.go:522 +0x1b5^@github.com/myitcv/govim/internal/plugin.Driver.do.func1(0xc000043d80)^@^I/home/frew/code/dotfiles/vim/pack/vanilla/start/govim/internal/plugin/pl
ugin.go:53 +0xd4^@panic(0x602260, 0x801d10)^@^I/home/frew/sdk/go1.12.9/src/runtime/panic.go:522 +0x1b5^@main.(*vimstate).complete(0xc0000aa140, 0xc0001b8cc0, 0x2, 0x4, 0x0, 0x0, 0x4ce84b, 0x4
cac5e)^@^I/home/frew/code/dotfiles/vim/pack/vanilla/start/govim/cmd/govim/complete.go:51 +0xac^@github.com/myitcv/govim/internal/plugin.Driver.doFunction.func1.1(0x8, 0x65ca38)^@^I/home/frew/
code/dotfiles/vim/pack/vanilla/start/govim/internal/plugin/plugin.go:188 +0x50^@github.co
```

(note that the actual file should not have that error, the contents are basically `package main` and an in progress function, which I was trying to autocomplete for; this happened while investigating #471 )

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?

Maybe this? 

```2019-08-29T06:59:25.345514_#1: gopls client start =======================
2019-08-29T06:59:25.345514_#1: LogMessage callback: &protocol.LogMessageParams{Type:1, Message:"could not find token.File for diagnostic: GetAST: unable to check package for file:///home/frew/code/zr0/infrastructure/stevedore/build.go: context canceled\n\tfile = file:///home/frew/code/zr0/infrastructure/stevedore/build.go"}
2019-08-29T06:59:25.345514_#1: gopls client end =======================
2019-08-29T06:59:25.346287_#1: gopls client start =======================
2019-08-29T06:59:25.346287_#1: LogMessage callback: &protocol.LogMessageParams{Type:1, Message:"failed to deliver diagnostic (will retry): GetAST: unable to check package for file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go: context canceled\n\tfile = file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go"}
2019-08-29T06:59:25.346287_#1: gopls client end =======================
2019-08-29T06:59:25.346886_#1: gopls client start =======================
2019-08-29T06:59:25.346886_#1: LogMessage callback: &protocol.LogMessageParams{Type:1, Message:"unable to check package: context canceled\n\tfile = file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go"}
2019-08-29T06:59:25.346886_#1: gopls client end =======================
2019-08-29T06:59:25.347189_#1: gopls client start =======================
2019-08-29T06:59:25.347189_#1: LogMessage callback: &protocol.LogMessageParams{Type:1, Message:"could not find token.File for diagnostic: GetAST: unable to check package for file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go: context canceled\n\tfile = file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go"}
2019-08-29T06:59:25.347189_#1: gopls client end =======================
2019-08-29T06:59:25.347724_#1: gopls client start =======================
2019-08-29T06:59:25.347724_#1: LogMessage callback: &protocol.LogMessageParams{Type:1, Message:"failed to deliver diagnostic (will retry): GetAST: unable to check package for file:///home/frew/code/zr0/infrastructure/stevedore/build.go: context canceled\n\tfile = file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go"}
2019-08-29T06:59:25.347724_#1: gopls client end =======================
2019-08-29T06:59:25.348700_#1: gopls client start =======================
2019-08-29T06:59:25.348700_#1: LogMessage callback: &protocol.LogMessageParams{Type:1, Message:"failed to deliver diagnostic for (will not retry): GetAST: unable to check package for file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go: context canceled\n\tfile = file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go"}
2019-08-29T06:59:25.348700_#1: gopls client end =======================
2019-08-29T06:59:25.366370_#1: gopls client start =======================
2019-08-29T06:59:25.366370_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.366370_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/core.go",
2019-08-29T06:59:25.366370_#1:     Version:     0,
2019-08-29T06:59:25.366370_#1:     Diagnostics: {
2019-08-29T06:59:25.366370_#1:     },
2019-08-29T06:59:25.366370_#1: }
2019-08-29T06:59:25.366370_#1: gopls client end =======================
2019-08-29T06:59:25.366997_#1: gopls client start =======================
2019-08-29T06:59:25.366997_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.366997_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/fromdag.go",
2019-08-29T06:59:25.366997_#1:     Version:     0,
2019-08-29T06:59:25.366997_#1:     Diagnostics: {
2019-08-29T06:59:25.366997_#1:     },
2019-08-29T06:59:25.366997_#1: }
2019-08-29T06:59:25.366997_#1: gopls client end =======================
2019-08-29T06:59:25.367354_#1: gopls client start =======================
2019-08-29T06:59:25.367354_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.367354_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/list.go",
2019-08-29T06:59:25.367354_#1:     Version:     0,
2019-08-29T06:59:25.367354_#1:     Diagnostics: {
2019-08-29T06:59:25.367354_#1:     },
2019-08-29T06:59:25.367354_#1: }
2019-08-29T06:59:25.367354_#1: gopls client end =======================
2019-08-29T06:59:25.367688_#1: gopls client start =======================
2019-08-29T06:59:25.367688_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.367688_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/parsedockerfile.go",
2019-08-29T06:59:25.367688_#1:     Version:     0,
2019-08-29T06:59:25.367688_#1:     Diagnostics: {
2019-08-29T06:59:25.367688_#1:     },
2019-08-29T06:59:25.367688_#1: }
2019-08-29T06:59:25.367688_#1: gopls client end =======================
2019-08-29T06:59:25.368035_#1: gopls client start =======================
2019-08-29T06:59:25.368035_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.368035_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/prune.go",
2019-08-29T06:59:25.368035_#1:     Version:     0,
2019-08-29T06:59:25.368035_#1:     Diagnostics: {
2019-08-29T06:59:25.368035_#1:     },
2019-08-29T06:59:25.368035_#1: }
2019-08-29T06:59:25.368035_#1: gopls client end =======================
2019-08-29T06:59:25.368350_#1: gopls client start =======================
2019-08-29T06:59:25.368350_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.368350_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/push.go",
2019-08-29T06:59:25.368350_#1:     Version:     0,
2019-08-29T06:59:25.368350_#1:     Diagnostics: {
2019-08-29T06:59:25.368350_#1:     },
2019-08-29T06:59:25.368350_#1: }
2019-08-29T06:59:25.368350_#1: gopls client end =======================
2019-08-29T06:59:25.368601_#1: gopls client start =======================
2019-08-29T06:59:25.368601_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.368601_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/stevedore.go",
2019-08-29T06:59:25.368601_#1:     Version:     0,
2019-08-29T06:59:25.368601_#1:     Diagnostics: {
2019-08-29T06:59:25.368601_#1:     },
2019-08-29T06:59:25.368601_#1: }
2019-08-29T06:59:25.368601_#1: gopls client end =======================
2019-08-29T06:59:25.368844_#1: gopls client start =======================
2019-08-29T06:59:25.368844_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.368844_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/checkmatch.go",
2019-08-29T06:59:25.368844_#1:     Version:     0,
2019-08-29T06:59:25.368844_#1:     Diagnostics: {
2019-08-29T06:59:25.368844_#1:     },
2019-08-29T06:59:25.368844_#1: }
2019-08-29T06:59:25.368844_#1: gopls client end =======================
2019-08-29T06:59:25.369077_#1: gopls client start =======================
2019-08-29T06:59:25.369077_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.369077_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/commands.go",
2019-08-29T06:59:25.369077_#1:     Version:     0,
2019-08-29T06:59:25.369077_#1:     Diagnostics: {
2019-08-29T06:59:25.369077_#1:     },
2019-08-29T06:59:25.369077_#1: }
2019-08-29T06:59:25.369077_#1: gopls client end =======================
2019-08-29T06:59:25.369301_#1: gopls client start =======================
2019-08-29T06:59:25.369301_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.369301_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/gittag.go",
2019-08-29T06:59:25.369301_#1:     Version:     0,
2019-08-29T06:59:25.369301_#1:     Diagnostics: {
2019-08-29T06:59:25.369301_#1:     },
2019-08-29T06:59:25.369301_#1: }
2019-08-29T06:59:25.369301_#1: gopls client end =======================
2019-08-29T06:59:25.369547_#1: gopls client start =======================
2019-08-29T06:59:25.369547_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.369547_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/main.go",
2019-08-29T06:59:25.369547_#1:     Version:     0,
2019-08-29T06:59:25.369547_#1:     Diagnostics: {
2019-08-29T06:59:25.369547_#1:     },
2019-08-29T06:59:25.369547_#1: }
2019-08-29T06:59:25.369547_#1: gopls client end =======================
2019-08-29T06:59:25.370295_#1: gopls client start =======================
2019-08-29T06:59:25.370295_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.370295_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/build.go",
2019-08-29T06:59:25.370295_#1:     Version:     0,
2019-08-29T06:59:25.370295_#1:     Diagnostics: {
2019-08-29T06:59:25.370295_#1:         {
2019-08-29T06:59:25.370295_#1:             Range: protocol.Range{
2019-08-29T06:59:25.370295_#1:                 Start: protocol.Position{Line:250, Character:37},
2019-08-29T06:59:25.370295_#1:                 End:   protocol.Position{Line:250, Character:37},
2019-08-29T06:59:25.370295_#1:             },
2019-08-29T06:59:25.370295_#1:             Severity:           1,
2019-08-29T06:59:25.370295_#1:             Code:               nil,
2019-08-29T06:59:25.370295_#1:             Source:             "LSP",
2019-08-29T06:59:25.370295_#1:             Message:            "too few arguments in call to runDebugShell",
2019-08-29T06:59:25.370295_#1:             Tags:               nil,
2019-08-29T06:59:25.370295_#1:             RelatedInformation: nil,
2019-08-29T06:59:25.370295_#1:         },
2019-08-29T06:59:25.370295_#1:     },
2019-08-29T06:59:25.370295_#1: }
2019-08-29T06:59:25.370295_#1: gopls client end =======================
2019-08-29T06:59:25.370545_#1: gopls client start =======================
2019-08-29T06:59:25.370545_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.370545_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/deploy.go",
2019-08-29T06:59:25.370545_#1:     Version:     0,
2019-08-29T06:59:25.370545_#1:     Diagnostics: {
2019-08-29T06:59:25.370545_#1:     },
2019-08-29T06:59:25.370545_#1: }
2019-08-29T06:59:25.370545_#1: gopls client end =======================
2019-08-29T06:59:25.370780_#1: gopls client start =======================
2019-08-29T06:59:25.370780_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.370780_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/orderdeps.go",
2019-08-29T06:59:25.370780_#1:     Version:     0,
2019-08-29T06:59:25.370780_#1:     Diagnostics: {
2019-08-29T06:59:25.370780_#1:     },
2019-08-29T06:59:25.370780_#1: }
2019-08-29T06:59:25.370780_#1: gopls client end =======================
2019-08-29T06:59:25.371581_#1: gopls client start =======================
2019-08-29T06:59:25.371581_#1: PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{
2019-08-29T06:59:25.371581_#1:     URI:         "file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go",
2019-08-29T06:59:25.371581_#1:     Version:     0,
2019-08-29T06:59:25.371581_#1:     Diagnostics: {
2019-08-29T06:59:25.371581_#1:         {
2019-08-29T06:59:25.371581_#1:             Range: protocol.Range{
2019-08-29T06:59:25.371581_#1:                 Start: protocol.Position{Line:3, Character:1},
2019-08-29T06:59:25.371581_#1:                 End:   protocol.Position{Line:3, Character:9},
2019-08-29T06:59:25.371581_#1:             },
2019-08-29T06:59:25.371581_#1:             Severity:           1,
2019-08-29T06:59:25.371581_#1:             Code:               nil,
2019-08-29T06:59:25.371581_#1:             Source:             "LSP",
2019-08-29T06:59:25.371581_#1:             Message:            "undeclared name: fmt",
2019-08-29T06:59:25.371581_#1:             Tags:               nil,
2019-08-29T06:59:25.371581_#1:             RelatedInformation: nil,
2019-08-29T06:59:25.371581_#1:         },
2019-08-29T06:59:25.371581_#1:     },
2019-08-29T06:59:25.371581_#1: }
```

### How did you install `govim`?
Vim 8 packages

### What did you do?

Started a new function in a new file, added `package main` to the top of the file and tried to tab complete via `fmt.<c-x><c-o>`

### What did you expect to see?

A list of completions.

### What did you see instead?

The exception from `:messages`

**Comment by myitcv** [comment]
Thanks for the report. Are you able to reproduce this in a simple `main` package in its own module?

**Comment by frioux** [comment]
Yes.  Single new directory, with a single file (in my case called `main.go`) with these contents:

```golang
package main

func main() {
   fmt.Pri<c-x><c-o>
}
```

I know that without "fmt" imported this is likely to fail, but it shouldn't do this, right?

**Comment by myitcv** [comment]
Thanks. I can't reproduce this for some reason. If you have specific steps, starting from scratch that would be helpful. Here's what I tried:

```
cd $(mktemp -d)
go mod init mod
cat <<EOD > main.go
package main

func main() {
    fmt.Pri
}
EOD
vi main.go
```

Then attempted completion via `<C-x><C-o>` at the end of line 4.

FWIW, the error messages you reported from `:messages` look different:

```
GetAST: unable to check package for file:///home/frew/code/zr0/infrastructure
/stevedore/debugshell.go: no packages found for file:///home/frew/code/zr0/infrastructure/stevedore/debugshell.go
```

i.e. it looks like `gopls` has got itself into a bit of a spin... and then the completion request fails as a derivative error.

**Comment by frioux** [comment]
Bizarre; I can't repro right now either.  One thing to note is that I *did* forget to create the mod file so it's possible some other vim instance was interacting with the current one, maybe, in case it found some go.mod high up in the hierarchy? (note that I *dont'* have one, eg, in `~` or `/tmp`.)

**Comment by myitcv** [comment]
Strange indeed. Do you want to close this for now then? We can always re-open if you can repro.

**Comment by frioux** [comment]
yep, will do.
